/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package elevators_project;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintStream;
import java.util.Scanner;

class AppTest {
    // private final static InputStream systemIn = System.in;
    // private final static PrintStream systemOut = System.out;

    // private static ByteArrayInputStream testIn;
    // private static ByteArrayOutputStream testOut;

    // @BeforeAll
    // public static void setUpOutput() {
    // testOut = new ByteArrayOutputStream();
    // System.setOut(new PrintStream(testOut));
    // }

    // private static void provideInput(String data) {
    // testIn = new ByteArrayInputStream(data.getBytes());
    // System.setIn(testIn);
    // }

    // private String getOutput() {
    // return testOut.toString();
    // }

    // @AfterAll
    // public static void restoreSystemInputOutput() {
    // System.setIn(systemIn);
    // System.setOut(systemOut);
    // }

    // @Test
    // public void testCase1() {
    // final String testString = "-1";
    // final String expectedOutputString = "The number of storeys should be an
    // integer greater than 0. Please enter the correct number of storeys: ";
    // provideInput(testString);

    // try {
    // App.main(new String[0]);
    // } catch (IOException e) {
    // e.printStackTrace();
    // }

    // assertEquals(expectedOutputString, getOutput());
    // }
}
